const BET_SAGA_STATE = {
  PENDING: 'PENDING',
  WALLET_CHARGED: 'WALLET_CHARGED',
  GAME_CREATED: 'GAME_CREATED',
  COMPLETED: 'COMPLETED',
  COMPENSATING: 'COMPENSATING',
  FAILED: 'FAILED',
};

module.exports = { BET_SAGA_STATE };
