services:
  infra:
    build:
      context: .
      dockerfile: infra/Dockerfile
    container_name: casino-infra
    restart: unless-stopped
    ports:
      - "27017:27017"
      - "3306:3306"
      - "9092:9092"
      - "2181:2181"
    environment:
      MONGO_INITDB_ROOT_USERNAME: casino_admin
      MONGO_INITDB_ROOT_PASSWORD: casino_secret
      MONGO_INITDB_DATABASE: casino_db
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: casino_db
      MYSQL_USER: casino_user
      MYSQL_PASSWORD: casino_pass
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://infra:9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    volumes:
      - infra-mongodb:/data/db
      - infra-mysql:/var/lib/mysql
      - infra-kafka:/opt/kafka/data
      - infra-zookeeper:/tmp/zookeeper
    networks:
      - casino-net
    healthcheck:
      test: ["CMD-SHELL","bash -c 'nc -z localhost 27017 && nc -z localhost 3306 && nc -z localhost 9092 && nc -z localhost 2181'"]
      interval: 20s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: infra/backend/Dockerfile
    container_name: casino-backend
    restart: unless-stopped
    depends_on:
      - infra
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://casino_admin:casino_secret@infra:27017/casino_db?authSource=admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: infra:9092
      DATABASE_URL: mysql+pymysql://casino_user:casino_pass@infra:3306/casino_db
      KAFKA_BOOTSTRAP_SERVERS: infra:9092
      WALLET_SERVICE_URL: http://localhost:8082
      AUDIT_SERVICE_URL: http://localhost:8084
      PORT: 8083
      JWT_SECRET: casino_jwt_super_secret_2025
      EUREKA_SERVER_URL: http://localhost:8761/eureka/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka/
      SPRING_KAFKA_CONSUMER_GROUP_ID: audit-consumer-group
    networks:
      - casino-net
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:8081/auth/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: casino-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - casino-net
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  casino-net:
    driver: bridge

volumes:
  infra-mongodb:
  infra-mysql:
  infra-kafka:
  infra-zookeeper:
